// File generated by manual configuration for Web and Android.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDFArTrn--xdxZzNTYysDv_ilMeOwNUaA',
    authDomain: 'campusflow-cd63e.firebaseapp.com',
    projectId: 'campusflow-cd63e',
    storageBucket: 'campusflow-cd63e.firebasestorage.app',
    messagingSenderId: '11843463495',
    appId: '1:11843463495:web:ce0a8a62d4d42b44d14462',
    databaseURL: 'https://campusflow-cd63e-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDFArTrn--xdxZzNTYysDv_ilMeOwNUaA',
    appId: '1:11843463495:android:c4a6b2b7b4a6b2b7b4a6b2',
    messagingSenderId: '11843463495',
    projectId: 'campusflow-cd63e',
    storageBucket: 'campusflow-cd63e.firebasestorage.app',
    databaseURL: 'https://campusflow-cd63e-default-rtdb.firebaseio.com',
  );
}
